server:
  port: 28120


spring:
  profiles:
    active: ${SPRING_PROFILES:config-server-nacos}
  application:
    name: monitor
  cloud:
    nacos:
      username: ${NACOS_USER:nacos}
      password: ${NACOS_PWD:nacos}
      discovery:
        server-addr: ${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
        namespace: ${NACOS_NAMESPACE:public}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
fist:
  jackson:
    customize:
      enabled: false
      excludeModules: NumberToStr

---
spring:
  config:
    activate:
      on-profile: config-server-nacos
    import:
      - optional:nacos:application.yml
      - optional:nacos:${spring.application.name}.yml
  cloud:
    nacos:
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        namespace: ${NACOS_NAMESPACE:public}
