server:
  port: 28090

spring:
  profiles:
    active: ${SPRING_PROFILES:config-server-nacos}
  application:
    name: platform-iam
  cloud:
    nacos:
      username: ${NACOS_USER:nacos}
      password: ${NACOS_PWD:nacos}
      discovery:
        metadata:
          api-docs-path: ${springdoc.api-docs.path:/v3/api-docs}
          management:
            context-path: ${management.context-path:/actuator}
        server-addr: ${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
        namespace: ${NACOS_NAMESPACE:public}
        group: ${NACOS_GROUP:DEFAULT_GROUP}

---
spring:
  config:
    activate:
      on-profile: config-server-nacos
    import:
      - nacos:application.yml
      - nacos:${spring.application.name}.yml
  cloud:
    nacos:
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        namespace: ${NACOS_NAMESPACE:public}
